# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: stenelind
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shui-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::711387100461:role/LambdaDynamoDBFull

functions:
  PostMessages:
    handler: functions/PostMessages/index.handler
    events:
      - httpApi:
          path: /api/messages
          method: post

  GetMessages:
    handler: functions/GetMessages/index.handler
    events:
      - httpApi:
          path: /api/getmessages
          method: get

  UpdateMessages:
    handler: functions/UpdateMessage/index.handler
    events:
      - httpApi:
          path: /api/updatemessage/{id} 
          method: put  

  DeleteMessages:
    handler: functions/DeleteMessage/index.handler
    events:
      - httpApi:
          path: /api/deletemessage/{id} 
          method: delete              

resources:
  Resources:
    BonzaiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'shui-db'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

